name: E2E (Cypress)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PROJECT_DIR: orangehrm-cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug layout
        run: |
          echo "PWD: $PWD"
          ls -la
          echo "--- $PROJECT_DIR ---"
          ls -la "$PROJECT_DIR"

      - name: Ensure package.json exists
        run: |
          test -f "$PROJECT_DIR/package.json" || { echo "❌ package.json not found in $PROJECT_DIR"; exit 1; }

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Type check
        working-directory: ${{ env.PROJECT_DIR }}
        run: npx tsc -p tsconfig.json --noEmit

      - name: Run Cypress (Chrome)
        uses: cypress-io/github-action@v6
        with:
          working-directory: ${{ env.PROJECT_DIR }}
          browser: chrome
          spec: cypress/e2e/**/*.cy.ts
          config-file: cypress.config.ts
          install: false            # мы уже сделали npm ci выше
          config: video=true
        env:
          CYPRESS_ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
          CYPRESS_ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ${{ env.PROJECT_DIR }}/cypress/screenshots
          if-no-files-found: igno
