name: E2E (Docker, Chrome)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image (chrome only)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: PROJECT_DIR=orangehrm-cypress
          tags: qa-cypress:chrome
          load: true                  # загрузить образ в докер раннера
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Cypress (Chrome)
        run: |
          mkdir -p artifacts/videos artifacts/screenshots
          docker run --rm --shm-size=2g --ipc=host \
            -e ORANGEHRM_USERNAME="${{ secrets.ORANGEHRM_USERNAME }}" \
            -e ORANGEHRM_PASSWORD="${{ secrets.ORANGEHRM_PASSWORD }}" \
            -e BROWSER="chrome" \
            -v "${{ github.workspace }}/artifacts/videos:/e2e/cypress/videos" \
            -v "${{ github.workspace }}/artifacts/screenshots:/e2e/cypress/screenshots" \
            qa-cypress:chrome

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: artifacts/screenshots
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: artifacts/videos
          if-no-files-found: ignore
          retention-days: 7
